name: "Deploy updated lambdas"

on:
  push:
    branches:
      - main

jobs:
  find-updated-directory:
    name: "Find updated directory"
    runs-on: ubuntu-latest
    outputs:
      changed_directories: ${{ steps.set-output.outputs.changed_directories }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed directories
        id: changed-directories
        uses: tj-actions/changed-files@v42
        with:
          dir_names: true
          dir_names_max_depth: 3
          json: true
          quotepath: false
      - name: "Set output in the matrix format"
        id: set-output
        run: |
          echo "${{ steps.changed-directories.outputs.all_changed_files }}"
          echo "changed_directories={\"dir\":${{ steps.changed-directories.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

  print-out-changed-directories:
    name: "Print out changed directories"
    runs-on: ubuntu-latest
    if: ${{ needs.find-updated-directory.outputs.changed_directories != '' }}
    strategy:
      matrix: ${{fromJson(needs.find-updated-directory.outputs.changed_directories)}}
    needs:
      - find-updated-directory

    steps:
      - uses: actions/checkout@v4
      - name: "Print out changed directories"
        run: |
          echo "Changed directories: ${{ matrix.dir }}"
